name: katana_theme
description: Base package for providing simple and straightforward theme definitions on Flutter.
version: 3.0.8
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_theme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  meta:
  katana: ^3.1.5
  katana_theme_annotation: ^3.0.6
  katana_platform_info: ^3.1.2
  path_provider: ^2.1.3
  flutter_svg: ^2.0.9
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  
