name: katana_test
description: Base package containing utilities for testing. It provides the base part of the Masamune framework.
version: 3.0.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_test

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
