name: masamune_markdown
description: Masamune package that allows for displaying and editing Markdown.
version: 3.5.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_markdown

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  katana: ^3.4.0
  masamune: ^3.5.6
  font_awesome_flutter: ^10.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
