name: katana_model
description: A package that models data into documents and collections and allows Firestore, local DB, and data mocks to be handled in the same interface.
version: 2.5.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_model

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.2.2

dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  import_sorter: ^4.6.0
