name: katana_model
description: A package that models data into documents and collections and allows Firestore, local DB, and data mocks to be handled in the same interface.
version: 3.3.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_model

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  
  freezed: ^3.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  import_sorter: ^4.6.0
