name: masamune_calendar
description: Masamune plugin to provide calendar functionality. The masamune framework is assumed to be used.
version: 2.1.29
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_calendar

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.9.2
  masamune: ^2.6.2
  simple_gesture_detector: ^0.2.0
dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
