name: masamune_calendar
description: Masamune plugin to provide calendar functionality. The masamune framework is assumed to be used.
version: 3.1.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  masamune: ^3.5.3
  simple_gesture_detector: ^0.2.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
