name: masamune_purchase_stripe
description: Masamune framework plugin for billing with Stripe; requires registration with Stripe.
version: 3.6.41
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase_stripe

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.2
  masamune: ^3.2.0
  flutter_inappwebview: ^6.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.1
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^3.0.10
  freezed: ^3.0.0
  json_serializable: ^6.6.0

