name: masamune_purchase_stripe
description: Masamune framework plugin for billing with Stripe; requires registration with Stripe.
version: 3.3.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase_stripe

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.3.3
  masamune: ^2.4.1
  flutter_inappwebview: ^5.7.2+3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.7.4
  freezed: ^2.3.2
  json_serializable: ^6.6.0

