name: masamune_purchase
description: Masamune plugin package that contains the base implementation for implementing InAppPurchase and an adapter for mocking.
version: 2.1.54
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.28
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.15.6
  freezed: ^2.3.2
  json_serializable: ^6.6.0

