name: masamune_purchase
description: Masamune plugin package that contains the base implementation for implementing InAppPurchase and an adapter for mocking.
version: 3.0.22
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.5
  masamune: ^3.3.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^3.0.14
  freezed: ^3.0.0
  json_serializable: ^6.6.0

