name: katana_cli
description: Command line tool for Masamune/Katana Framework. It initializes the project and initializes the services.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_cli

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  yaml: ^3.1.0
  yaml_writer: ^2.0.0
  archive: ^3.1.9
  csv: ^6.0.0
  katana: ^3.0.0-dev.0
  image: ^4.0.10
  xml: ^6.2.2
  flutter_lints: ^3.0.0
  html: ^0.15.1

executables:
  katana:
dev_dependencies:
  import_sorter: ^4.6.0
