name: katana_cli
description: Command line tool for Masamune/Katana Framework. It initializes the project and initializes the services.
version: 3.5.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_cli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  yaml_writer: ^2.0.1
  archive: ^4.0.0
  csv: ^6.0.0
  katana: ^3.1.2
  image: ^4.5.0
  xml: ^6.5.0
  flutter_lints: ^5.0.0
  html: ^0.15.5
  http: ^1.1.0
  googleapis_auth: ^1.4.1

executables:
  katana:
dev_dependencies:
  import_sorter: ^4.6.0
