name: masamune
description: An application development framework centered on automatic code generation using build_runner.
version: 3.3.12
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^3.2.1
  katana_logger: ^3.0.10
  katana_shorten: ^3.0.8
  katana_indicator: ^3.0.8
  katana_scoped: ^3.0.11
  katana_model: ^3.3.5
  katana_model_local: ^3.1.17
  katana_router: ^3.1.10
  katana_theme: ^3.0.11
  katana_localization: ^3.0.12
  katana_form: ^3.1.13
  katana_auth: ^3.0.10
  katana_ui: ^3.1.3
  katana_storage: ^3.0.8
  katana_functions: ^3.0.8
  katana_platform_info: ^3.1.4
  masamune_annotation: ^3.0.10
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  