name: masamune_ads_google
description: Masamune plugin package for GoogleAd. Plug-in package for displaying interstitial, native, and reward ads.
version: 2.4.26
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_ads_google

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.12.1
  masamune: ^2.10.4
  google_mobile_ads: ^3.0.0
  permission_handler: ^11.1.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
