name: masamune_location_background
description: Masamune plugin library for handling background location information in apps.
version: 3.0.16
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location_background

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.4
  masamune: ^3.3.2
  background_locator_2: ^2.0.6
  path_provider: ^2.1.3
  permission_handler: ^11.0.0
  masamune_location_platform_interface: ^3.0.16
  shared_preferences: ^2.5.3

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

