name: masamune_introduction
description: Masamune plugin package for displaying an introduction description screen.
version: 3.4.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_introduction

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.3.0
  masamune: ^3.5.1
  introduction_screen: ^3.1.16

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^3.1.2


