name: masamune_model_docs_builder
description: A builder package to generate table and schema definitions for Firebase and databases from Masamune model definitions, output in Markdown tabular format.
version: 3.2.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_docs_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.4.0
  katana_builder: ^3.2.3
  build: ^3.1.0
  dart_style: ^3.1.1
  code_builder: ^4.11.0
  source_gen: ^3.1.0
  analyzer: ^8.0.0
  http: ^1.5.0
  masamune_annotation: ^3.1.1
  masamune_builder: ^3.1.4
  glob: ^2.1.3
dev_dependencies:
  test: ^1.26.3
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
