name: masamune_camera
description: Masamune plug-in package for simple use of the camera.
version: 3.3.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_camera

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  masamune: ^3.5.3
  # TODO: 0.11移行ではAndroidだと落ちてしまうので、0.10に戻す
  camera: ^0.10.0
  image: ^4.2.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.0

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^3.1.3


