name: katana_auth_firebase
description: Firebase plugin for katana_auth. A package to facilitate switching between Local and Firebase authentication implementations.
version: 2.7.12
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_auth_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.17.0
  katana_auth: ^2.10.8
  katana_firebase: ^2.2.14
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  shared_preferences: ^2.0.15
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.2
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
