name: masamune_firebase_app_check
description: Plug-in to make Firebase App Check available on Masamune Framework.
version: 2.3.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_firebase_app_check

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.18.1
  masamune: ^2.23.2
  katana_firebase: ^2.2.16
  firebase_core: ^3.5.0
  firebase_app_check: ^0.3.2+3
  universal_platform: ^1.0.0+1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.3
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
