name: masamune_location_platform_interface
description: Masamune plugin library for handling location information in apps.
version: 2.3.2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location_platform_interface

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.11.0
  masamune: ^2.8.2

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

