name: katana_flutter
description: Package containing a collection of basic Flutter utilities. It provides the base part of the Masamune framework.
version: 0.13.0+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  katana: ^0.13.0
  csv: ^5.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  connectivity_plus: ^2.3.6
  device_info_plus: ^4.0.1
  package_info_plus: ^1.4.3
  path_provider: ^2.0.11
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
