name: katana_listenables
description: The base part of the package that allows Listenable values to be grouped together and treated as a ChangeNotifier.
version: 2.2.5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_listenables

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.13.2
  katana_listenables_annotation: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  katana_listenables_builder: ^2.1.6
