name: katana_listenables
description: The base part of the package that allows Listenable values to be grouped together and treated as a ChangeNotifier.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_listenables

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.0.0-dev.0
  katana_listenables_annotation: ^3.0.0-dev.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  katana_listenables_builder: ^3.0.0-dev.0
