name: katana_auth
description: Base package to facilitate switching between Local and Firebase authentication implementations.
version: 2.11.5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_auth

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.20.1
  katana_logger: ^2.5.5
  path_provider: ^2.1.3
  shared_preferences: ^2.0.15

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.4
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
