name: katana_auth
description: Base package to facilitate switching between Local and Firebase authentication implementations.
version: 3.0.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_auth

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.0
  katana_logger: ^3.0.1
  path_provider: ^2.1.3
  shared_preferences: ^2.0.15

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
