name: masamune_logger_firebase
description: Plug-in package to easily add Firebase Analytics, Performance and Crashlytics on Masamune Framework. The functionality is available by simply adding an Adapter.
version: 2.2.113
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_logger_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  masamune: ^2.15.1
  katana_firebase: ^2.2.11
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_analytics: ^11.3.2
  firebase_performance: ^0.10.0+7

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.2
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
