name: masamune_model_firebase_data_connect_builder
description: Builder package to automatically generate GraphQL code for Firebase Data Connect.
version: 2.0.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_data_connect_builder

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  katana: ^2.15.2
  katana_builder: ^2.1.10
  yaml: ^3.1.0
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.10.0
  source_gen: ^1.2.2
  analyzer: ^6.4.0
  http: ^1.0.0
  glob: ^2.1.0
  masamune_model_firebase_data_connect_annotation: ^2.1.3
  masamune_builder: ^2.17.6
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.1
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
