name: masamune_model_firebase_data_connect_builder
description: Builder package to automatically generate GraphQL code for Firebase Data Connect.
version: 3.0.11
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_data_connect_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.1.3
  katana_builder: ^3.0.5
  yaml: ^3.1.2
  build: ^2.4.1
  dart_style: ^3.0.0
  code_builder: ^4.10.1
  source_gen: ^2.0.0
  analyzer: ^7.0.0
  http: ^1.2.2
  glob: ^2.1.2
  masamune_model_firebase_data_connect_annotation: ^3.0.6
  masamune_builder: ^3.0.11
dev_dependencies:
  test: ^1.25.8
  katana_test: ^3.0.2
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
