name: masamune_notification_firebase
description: Package for receiving PUSH notifications using Firebase Messaging. Firebase Functions can also be used to send notifications.
version: 2.7.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_notification_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  masamune: ^2.13.35
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  katana_firebase: ^2.2.6
  universal_platform: ^1.0.0+1
  masamune_notification: ^2.7.1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.15.8
  freezed: ^2.3.2
  json_serializable: ^6.6.0
