name: masamune_builder
description: Building system for masamune framework. Automatic creation of models, themes, pages, and translation data.
version: 3.1.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.4.0
  katana_builder: ^3.2.3
  build: ^3.1.0
  dart_style: ^3.1.1
  code_builder: ^4.11.0
  source_gen: ^3.1.0
  analyzer: ^8.0.0
  http: ^1.5.0
  freezed_annotation: ^3.1.0
  katana_theme_builder: ^3.1.3
  katana_theme_annotation: ^3.1.1
  katana_localization_builder: ^3.2.3
  katana_localization_annotation: ^3.2.1
  katana_router_builder: ^3.1.4
  katana_router_annotation: ^3.1.1
  masamune_annotation: ^3.1.1
dev_dependencies:
  test: ^1.26.3
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
