name: masamune_builder
description: Building system for masamune framework. Automatic creation of models, themes, pages, and translation data.
version: 3.0.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  katana: ^3.0.0
  katana_builder: ^3.0.0
  build: ^2.4.1
  dart_style: ^3.0.0
  code_builder: ^4.10.1
  source_gen: ^2.0.0
  analyzer: ^7.0.0
  http: ^1.2.2
  freezed_annotation: ^3.0.0
  katana_theme_builder: ^3.0.0
  katana_theme_annotation: ^3.0.0
  katana_localization_builder: ^3.0.0
  katana_localization_annotation: ^3.0.0
  katana_router_builder: ^3.0.0
  katana_router_annotation: ^3.0.0
  katana_listenables_annotation: ^3.0.0
  katana_listenables_builder: ^3.0.0
  katana_prefs_annotation: ^3.0.0
  katana_prefs_builder: ^3.0.0
  masamune_annotation: ^3.0.0
dev_dependencies:
  test: ^1.25.8
  katana_test: ^3.0.0
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
