name: masamune_builder
description: Building system for masamune framework. Automatic creation of models, themes, pages, and translation data.
version: 2.15.9
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  katana: ^2.15.1
  katana_builder: ^2.1.9
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  analyzer: ^6.0.0
  http: ^1.0.0
  freezed_annotation: ^2.2.0
  katana_theme_builder: ^2.3.6
  katana_theme_annotation: ^2.2.6
  katana_localization_builder: ^2.2.12
  katana_localization_annotation: ^2.2.9
  katana_router_builder: ^2.1.12
  katana_router_annotation: ^2.1.10
  katana_listenables_annotation: ^2.1.8
  katana_listenables_builder: ^2.1.9
  katana_prefs_annotation: ^2.1.8
  katana_prefs_builder: ^2.1.10
  masamune_annotation: ^2.6.11
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
