name: masamune_deeplink_firebase
description: Masamune plugin library for using Firebase DynamicLinks to launch applications from URLs and launch internal pages.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_deeplink_firebase

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.0.0-dev.1
  masamune: ^3.0.0-dev.0
  katana_firebase: ^3.0.0-dev.0
  firebase_dynamic_links: ^5.5.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

