name: masamune_deeplink_firebase
description: Masamune plugin library for using Firebase DynamicLinks to launch applications from URLs and launch internal pages.
version: 2.2.45
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_deeplink_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.13.2
  masamune: ^2.12.1
  katana_firebase: ^2.2.3
  firebase_dynamic_links: ^5.3.5
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

