name: masamune_deeplink_firebase
description: Masamune plugin library for using Firebase DynamicLinks to launch applications from URLs and launch internal pages.
version: 3.0.16
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_deeplink_firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.4
  masamune: ^3.3.2
  katana_firebase: ^3.0.6
  firebase_dynamic_links: ^6.0.7

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

