name: katana_model_openapi_builder
description: Building system for katana model open-api plugin packages. Create models of adapters and freezed available in katana_model from the open API yaml.
version: 2.1.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_model_openapi_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies: 
  katana: ^2.13.2
  katana_builder: ^2.1.6
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  analyzer: ^6.0.0
  yaml: ^3.1.1
  open_api_forked: ^3.0.0+6

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
