name: masamune_purchase_mobile
description: Masamune plugin library to implement in-app purchases for GooglePlay and AppStore.
version: 2.8.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase_mobile

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: in_app_purchase_android
      ios:
        default_package: in_app_purchase_storekit
      macos:
        default_package: in_app_purchase_storekit
      web:

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.12.1
  masamune: ^2.9.18
  universal_platform: ^1.0.0+1
  masamune_purchase: ^2.1.3
  in_app_purchase: ^3.1.7
  in_app_purchase_android: ^0.3.0+6
  in_app_purchase_storekit: ^0.3.6+4

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

