name: masamune_purchase_mobile
description: Masamune plugin library to implement in-app purchases for GooglePlay and AppStore.
version: 3.0.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_purchase_mobile

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: in_app_purchase_android
      ios:
        default_package: in_app_purchase_storekit
      macos:
        default_package: in_app_purchase_storekit
      web:

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.2
  masamune: ^3.0.6
  universal_platform: ^1.0.0+1
  masamune_purchase: ^3.0.6
  in_app_purchase: ^3.1.7
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.6+4

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.1
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

