name: masamune_text_to_speech
description: Masamune plug-in adapter for use with Text-to-Speech. Provides a controller.
version: 3.0.24
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_text_to_speech

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.0
  masamune: ^3.3.10
  flutter_tts: ^4.0.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

