name: katana_scoped
description: A state management package to allow for retention and management while specifying the scope of the state.
version: 3.1.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_scoped

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  katana_logger: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
