name: katana_theme_annotation
description: Annotation package for providing simple and straightforward theme definitions on Flutter.
version: 1.4.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_theme_annotation

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  katana: ^1.0.8
dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
