name: masamune_deeplink
description: Masamune plugin library to handle Deeplink. Launch the application from the URL to launch the internal page.
version: 2.2.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_deeplink

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.11.0
  masamune: ^2.8.1
  uni_links: ^0.5.1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

