name: masamune_model_firestore
description: A model adapter plugin that applies and expands on `katana_model_firestore` to retrieve data from Firestore.
version: 3.0.20
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firestore

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^3.1.5
  masamune: ^3.3.6
  katana_model_firestore: ^3.1.10
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  