name: masamune_model_algolia
description: Masamune plugin package that includes a model adapter to retrieve data from Algolia.
version: 3.0.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_algolia

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^3.1.1
  masamune: ^3.0.4
  algolia_helper_flutter: ^1.0.0
  katana_model_firestore: ^3.0.2
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  