name: masamune_model_algolia
description: Masamune plugin package that includes a model adapter to retrieve data from Algolia.
version: 2.4.75
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_algolia

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0

  katana: ^2.14.0
  masamune: ^2.13.31
  algolia_helper_flutter: ^0.5.0
  katana_model_firestore: ^2.16.32
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  