name: masamune_model_algolia
description: Masamune plugin package that includes a model adapter to retrieve data from Algolia.
version: 3.2.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_algolia

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^3.4.0
  masamune: ^3.5.5
  algolia_helper_flutter: ^1.0.0
  katana_model_firestore: ^3.3.3
  algolia_client_core: ^1.40.0
  algolia_client_insights: ^1.40.0
  algolia_client_search: ^1.40.0
  algoliasearch: ^1.40.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  