name: masamune_model_firestore_builder
description: Define a builder to describe Firestore rules; build using the masamune_annotation annotation.
version: 2.2.25
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firestore_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  katana: ^2.15.1
  katana_builder: ^2.1.9
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  analyzer: ^6.0.0
  http: ^1.0.0
  masamune_annotation: ^2.6.11
  masamune_builder: ^2.15.10
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
