name: masamune_painter
description: The Masamune package, which will enable drawing with touch or a stylus pen.
version: 3.3.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_painter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  katana: ^3.4.0
  masamune: ^3.5.2
  image_painter: ^0.7.1
  font_awesome_flutter: ^10.8.0
  flutter_colorpicker: ^1.1.0
  http: ^1.2.2
  shared_preferences: ^2.5.3
  vector_math: ^2.1.4
  two_dimensional_scrollables: ^0.3.7
  path: ^1.9.1
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
