name: masamune_painter
description: The Masamune package, which will enable drawing with touch or a stylus pen.
version: 3.1.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_painter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  katana: ^3.1.5
  masamune: ^3.3.8
  image_painter: ^0.7.1
  font_awesome_flutter: ^10.8.0
  flutter_colorpicker: ^1.1.0
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
