name: masamune_location_geocoding
description: Masamune plugin for using Google Map Geocoding API with Firebase Functions.
version: 3.0.15
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location_geocoding

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.3
  masamune: ^3.3.1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.2
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
