name: masamune_model_firebase_remote_config
description: Package that allows remote configurations to be retrieved as a Masamune framework documentation model.
version: 3.2.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:
  katana: ^3.4.0
  masamune: ^3.5.4
  katana_firebase: ^3.1.1
  firebase_remote_config: ^6.1.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  