name: masamune_model_firebase_remote_config
description: Package that allows remote configurations to be retrieved as a Masamune framework documentation model.
version: 3.0.24
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:
  katana: ^3.2.0
  masamune: ^3.3.10
  katana_firebase: ^3.0.8
  firebase_remote_config: ^5.4.0
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  