name: katana_storage_firebase
description: Firebase plugin for katana_storage. A package to facilitate switching between Local and Firebase storage implementations.
version: 2.1.13
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_storage_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.13.2
  katana_storage: ^2.2.6
  katana_firebase: ^2.2.4
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  path_provider: ^2.1.3
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
