name: masamune_lints
description: Package that defines lint rules necessary for use with the Masamune framework.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_lints

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  katana: ^3.0.0-dev.1
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.3
  custom_lint: ^0.6.4
  custom_lint_builder: ^0.6.4
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
