name: masamune_lints
description: Package that defines lint rules necessary for use with the Masamune framework.
version: 3.0.8
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_lints

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.2.0
  analyzer: ^7.0.0
  analyzer_plugin: ^0.13.0
  custom_lint: ^0.7.5
  custom_lint_builder: ^0.7.0
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
