name: katana_theme_builder
description: Building system for katana theme packages. Create a list of image assets from the Asset folder.
version: 2.4.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_theme_builder

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies: 
  katana: ^2.18.1
  katana_builder: ^2.2.2
  katana_theme_annotation: ^2.3.1
  build: ^2.4.1
  dart_style: ^3.0.0
  code_builder: ^4.10.1
  source_gen: ^2.0.0
  analyzer: ^7.0.0
  yaml: ^3.1.2
  glob: ^2.1.2

dev_dependencies:
  test: ^1.25.8
  katana_test: ^2.1.3
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
