name: katana_theme_builder
description: Building system for katana theme packages. Create a list of image assets from the Asset folder.
version: 3.1.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_theme_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  katana: ^3.4.0
  katana_builder: ^3.2.3
  katana_theme_annotation: ^3.1.1
  build: ^3.0.0
  dart_style: ^3.0.0
  code_builder: ^4.10.1
  source_gen: ^3.0.0
  analyzer: ^8.0.0
  yaml: ^3.1.2
  glob: ^2.1.2

dev_dependencies:
  test: ^1.25.8
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
