name: katana_router_annotation
description: Define annotations to use the Katana router builder. Build with katana_router_builder using this annotation.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router_annotation

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  katana: ^3.0.0-dev.0
  meta: ^1.8.0
    
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
