name: masamune_notification
description: Masamune plugin to use base classes and stubs to implement PUSH notifications.
version: 2.2.55
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_notification

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  masamune: ^2.4.113
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  masamune_scheduler: ^2.1.52
dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.9.8
  freezed: ^2.3.2
  json_serializable: ^6.6.0
