name: masamune_auth_apple
description: Authentication plugin for Masamune that can implement Apple sign-in, works only on IOS.
version: 3.0.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_apple

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.1
  masamune: ^3.0.3
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

