name: katana_logger
description: Base package for logging app performance and access status. Additional packages can be installed to use Firebase Analytics, etc.
version: 3.0.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_logger

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.4
  path_provider: ^2.1.3
  shared_preferences: ^2.5.3
  katana_platform_info: ^3.1.1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
