name: masamune_storage_functions
description: Masamune package for uploading files to storage using Functions.
version: 3.2.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_storage_functions

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:
  katana: ^3.4.0
  masamune: ^3.5.6
  katana_functions: ^3.1.1
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  