name: katana_localization_builder
description: Building system for katana localization packages. Automatic localization file generation.
version: 3.1.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_localization_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  katana: ^3.1.5
  katana_builder: ^3.0.7
  katana_localization_annotation: ^3.1.4
  build: ^2.4.1
  dart_style: ^3.0.0
  code_builder: ^4.10.1
  source_gen: ^2.0.0
  analyzer: ^7.0.0
  http: ^1.2.2
  csv: ^6.0.0
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.25.8
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
