name: masamune_model_firebase_data_connect_annotation
description: Define annotations to use the masamune firebase data connect builder. Build with masamune_model_firebase_data_connect_builder using this annotation.
version: 3.0.8
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_data_connect_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.1.5
  meta:
  masamune_annotation: ^3.0.8
    
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
