name: masamune_model_firebase_data_connect_annotation
description: Define annotations to use the masamune firebase data connect builder. Build with masamune_model_firebase_data_connect_builder using this annotation.
version: 2.1.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_data_connect_annotation

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  katana: ^2.15.1
  meta: ^1.8.0
  masamune_annotation: ^2.6.11
    
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
