name: masamune_speech_to_text_mobile
description: Masamune plug-in adapter for use with Speech-to-Text on mobile. Provides a controller.
version: 3.2.5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_speech_to_text_mobile

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  masamune: ^3.5.5
  masamune_speech_to_text: ^3.2.5
  speech_to_text: ^7.0.0
  speech_to_text_platform_interface: ^2.1.0
  permission_handler: ^12.0.0

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

