name: katana_prefs
description: The base part of the package for type-safe use of retrieving and storing Shared Preferences values, defining data in a Freezed-like fashion.
version: 2.0.21
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_prefs

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.5.0
  katana_prefs_annotation: ^2.0.18
  shared_preferences: ^2.0.16
dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
