name: masamune_auth_google
description: Authentication plugin for Masamune that can implement Google sign-in.
version: 3.0.23
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_google

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.0
  masamune: ^3.3.9
  google_sign_in: ^6.2.1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

