name: masamune_auth_google
description: Authentication plugin for Masamune that can implement Google sign-in.
version: 2.3.18
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_google

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.12.1
  masamune: ^2.9.15
  google_sign_in: ^6.1.4

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

