name: masamune_picker
description: Package for retrieving files such as images and videos from terminal storage, cameras, etc.
version: 3.1.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^10.2.0
  mime:
  image_picker: ^1.1.0
  katana: ^3.1.5
  masamune: ^3.3.4
  image: ^4.5.4
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
