name: masamune_picker
description: Package for retrieving files such as images and videos from terminal storage, cameras, etc.
version: 2.2.68
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_picker

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  file_picker: ^8.0.1
  flutter:
    sdk: flutter
    
  image_picker: ^1.1.0
  katana: ^2.14.0
  masamune: ^2.13.24
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
