name: katana_form
description: Package to provide FormController to define the use of forms and FormStyle to unify the look and feel of forms.
version: 2.15.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_form

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.16.1
  universal_platform: ^1.0.0+1
  flutter_rating_bar: ^4.0.1
  pin_input_text_field: ^4.5.1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.2
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
