name: masamune_module
description: Package in which various functions are modularized. The katana_routing routing system is used on the assumption that Riverpod is used.
version: 0.14.1+5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_module

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  masamune_ui: ^0.14.0
  photo_view: ^0.14.0
  flutter_quill: ^6.0.2
  tuple: ^2.0.0
  flutter_sliding_tutorial: ^1.1.3+3
  # flutter_quill_extensions: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
