name: masamune_speech_to_text_google
description: Masamune plug-in adapter for use with Speech-to-Text on Google. Provides a controller.
version: 3.2.4
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_speech_to_text_google

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  masamune: ^3.5.3
  google_speech: ^5.3.0
  masamune_speech_to_text: ^3.2.3
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.0
  masamune_google_cloud: ^3.2.4

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

