name: masamune_module_point_ecosystem
description: This Masamune plugin module provides a point-based monetization structure for your app.
version: 2.5.118
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_module_point_ecosystem

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.15.2
  masamune: ^2.14.11
  masamune_module: ^2.4.108
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  masamune_ads_google: ^2.5.10
  masamune_purchase: ^2.1.91
  masamune_purchase_mobile: ^2.8.92
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.1
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.17.6
  freezed: ^2.3.2
  json_serializable: ^6.6.0
