name: masamune_module_point_ecosystem
description: This Masamune plugin module provides a point-based monetization structure for your app.
version: 2.5.48
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_module_point_ecosystem

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.13.2
  masamune: ^2.12.0
  masamune_module: ^2.4.42
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  masamune_ads_google: ^2.4.42
  masamune_purchase: ^2.1.24
  masamune_purchase_mobile: ^2.8.25
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.15.2
  freezed: ^2.3.2
  json_serializable: ^6.6.0
