name: masamune_model_firebase_data_connect
description: Automatically generates GraphQL files for Firebase Data Connect from Collection and Document data schemes so that they can be used in applications.
version: 3.0.26
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_firebase_data_connect

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^3.2.1
  masamune: ^3.3.12
  masamune_model_firebase_data_connect_annotation: ^3.0.10
  katana_firebase: ^3.0.9
  firebase_data_connect: ^0.1.2
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  