name: masamune_model_firebase_data_connect
description: A model package for Masamune that automatically generates GraphQL files for Firebase Data Connect from Collection and Document data schemes so that they can be used in applications.
version: 2.0.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_data_connect

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  katana: ^2.15.2
  masamune: ^2.14.6
  masamune_model_firebase_data_connect_annotation: ^2.1.3
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.1
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  