name: masamune_agora
description: Plug-in for Masamune framework to use Agora.io. Includes support for recording.
version: 3.1.3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_agora

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
  masamune: ^3.5.3
  agora_rtc_engine: ^6.2.0
  permission_handler: ^12.0.0
  web: ^1.1.1
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
