name: katana_model_firestore
description: Firestore plugin for katana_model. A package that models data into documents and collections and allows Firestore, local DB, and data mocks to be handled in the same interface.
version: 2.16.33
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_model_firestore

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  katana: ^2.15.0
  katana_firebase: ^2.2.6
  katana_model: ^2.26.16
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  fake_cloud_firestore: ^2.5.1
