name: katana_firebase
description: Base package to handle firebase with Katana package. It performs initialization and other tasks.
version: 2.2.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_firebase

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  katana: ^2.15.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
