name: katana
description: Package containing a collection of basic Dart utilities. It provides the base part of the Masamune framework.
version: 3.1.5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl:
  meta:
  typed_data: ^1.3.0
  crypto: ^3.0.0
  uuid: ^4.4.0
  sprintf: ^7.0.0
  encrypt: ^5.0.1
  http: ^1.0.0
  recase: ^4.0.0

dev_dependencies:
  test: ^1.24.9
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
