name: masamune_ai_openai
description: Plug-in to make OpenAI API available on Masamune Framework. API key registration is required separately.
version: 2.7.58
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_ai_openai

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  katana_storage: ^2.2.7
  masamune: ^2.13.22
  path_provider: ^2.1.3
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
