name: katana_router_builder
description: Building system for katana router packages. Automatic Page route generation.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router_builder

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies: 
  katana: ^3.0.0-dev.0
  katana_builder: ^3.0.0-dev.0
  katana_router_annotation: ^3.0.0-dev.0
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  analyzer: ^6.0.0
  glob: ^2.1.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
