name: katana_router_builder
description: Building system for katana router packages. Automatic Page route generation.
version: 3.1.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  katana: ^3.3.0
  katana_builder: ^3.2.1
  katana_router_annotation: ^3.1.0
  build: ^3.1.0
  dart_style: ^3.1.1
  code_builder: ^4.11.0
  source_gen: ^3.1.0
  analyzer: ^7.0.0
  glob: ^2.1.3

dev_dependencies:
  test: ^1.26.3
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
