name: katana_shorten
description: Flutter package to write Duration, EdgeInsets, etc. in short descriptions. Simple widgets are also provided.
version: 3.1.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_shorten

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.4.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
