name: katana_storage
description: Base package to facilitate switching between Local and Firebase storage implementations.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_storage

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.0.0-dev.0
  path_provider: ^2.1.3
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
