name: katana_module
description: Package that defines a base class for modularization. It defines abstract classes, etc. for use with the Masamune module.
version: 0.9.2+60s
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_katana_module

environment:
  sdk: ">=2.13.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^0.9.0
  katana_routing: ^0.9.0
  model_notifier: ^0.9.0
  flutter_riverpod: ^1.0.3
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
