name: katana_builder
description: Base package containing utilities for builder. It provides the base part of the Masamune framework.
version: 3.0.2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.1.1
  analyzer: ^7.0.0

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
