name: katana_indicator
description: A package to make it easier to use Flutter's indicators (especially when waiting for processing in Future).
version: 1.1.15
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_indicator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^1.0.9
dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
