name: masamune_auth_firebase
description: Plug-in package for server-side integration of Firebase Authentication.
version: 3.0.20
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.1.5
  masamune: ^3.3.6
  katana_auth: ^3.0.8
  katana_firebase: ^3.0.7
  katana_auth_firebase: ^3.1.5

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

