name: masamune_speech_to_text
description: Masamune plug-in adapter for use with Speech-to-Text. Provides a controller.
version: 2.2.20
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_speech_to_text

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
    
  katana: ^2.12.1
  masamune: ^2.9.16
  speech_to_text: ^6.3.0
  universal_platform: ^1.0.0+1
  speech_to_text_platform_interface: ^2.1.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

