name: masamune_notification_local
description: Masamune plugin library for local PUSH notification. Only mobile can handle.
version: 2.2.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_notification_local

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  masamune: ^2.15.12
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_local_notifications: ^18.0.0
  universal_platform: ^1.0.0+1
  masamune_notification: ^2.9.17
  timezone: ^0.10.0
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.2
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^2.20.4
  freezed: ^2.3.2
  json_serializable: ^6.6.0
