name: masamune_notification_local
description: Masamune plugin library for local PUSH notification. Only mobile can handle.
version: 3.1.5
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_notification_local

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  masamune: ^3.5.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.0
  flutter_local_notifications: ^19.0.0
  masamune_notification: ^3.2.5
  timezone: ^0.10.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  masamune_builder: ^3.1.3
  freezed: ^3.0.0
  json_serializable: ^6.6.0
