name: masamune_test
description: This package is designed to test the Masamune framework.
version: 3.3.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_test

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
    
  meta:
  katana: ^3.4.0
  masamune: ^3.5.6
  alchemist: ^0.12.0
  test: ^1.29.0
  katana_test: ^3.1.0
dev_dependencies:
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
